In [ ]:
# Mini Project:
# Let us build a project to learn more about NumPy:

# Features of the data set:

# Age: Age of the person

# education-num: No. of years of education they had

# race: Person's race 0 - Amer-Indian-Eskimo
# 1 - Asian-Pac-Islander
# 2 - Black
# 3 - Other
# 4 - White

# sex: Person's gender 0 - Female
# 1 - Male

# capital-gain: Income from investment sources, apart from wages/salary

# capital loss: Losses from investment sources, apart from wages/salary

# hours-per-week: No. of hours per week the person works

# income: Annual Income of the person
# 0 : Less than or equal to 50K
# 1 : More than 50K

import numpy as np

data_file = "/content/makeSenseOfCensus.csv"

In [ ]:
# Step 1 : Read the Data!

# data_file ='makeSenseOfCensus.csv'
# Loading the data
# data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# # printing the data

# print("\nData: \n\n", data)
# Printing the type of data
# print("\nType of data: \n\n", type(data))

In [ ]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1, dtype= int) # skip = 1header will ignore the first row

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]


In [ ]:
# Step 2 : Append the Data
# Append 'new_record' (given) to 'data' using "np.concatenate()"¶
# new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

In [ ]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

In [ ]:
dataAlt = np.concatenate((data,new_record))


In [ ]:
print(dataAlt.shape)
print(data.shape)

(1001, 8)
(1000, 8)


In [ ]:
# Step 3 : Check if it's a young country or old country
# Create a new array called 'age' by taking only age 
# column(age is the column with index 0) of 'census' array.

# Find the max age and store it in a variable called 'max_age'.

# Find the min age and store it in a variable called 'min_age'.

# Find the mean of the age and store it in a variable called 'age_mean'.

# Find the standard deviation of the age and store it in a variable called 'age_std'

# HOW TO EXTRACT COLUMNS FROM NUMPY



In [ ]:





an_array = np.array([[1, 2, 3], [4, 5, 6]])
first_and_third_column = an_array[:, [0]]
print(first_and_third_column)

[[1]
 [4]]


In [ ]:
Age = dataAlt[:,[0]]

In [ ]:
print(Age)

[[39]
 [50]
 [38]
 ...
 [40]
 [39]
 [50]]


In [ ]:
Age = dataAlt[:,0]
print(Age)

[39 50 38 ... 40 39 50]


In [ ]:
# TO EXTRACT COLUMNS LINK

# https://www.kite.com/python/answers/how-to-extract-specific-columns-from-a-numpy-array-in-python

In [ ]:
MaxAge = np.max(Age)
print(MaxAge)

90


In [ ]:
MinAge = np.min(Age)
print(MinAge)

17


In [ ]:
AgeMean = np.average(Age)
print(round(AgeMean, 2))  # decimal trick

38.06


In [ ]:
stdAge = np.std(Age)
print(stdAge)

13.341478176165857


In [ ]:
# Step 4: Let's check the country's race distribution to identify the minorities
# Create four different arrays by subsetting 'census' array by 
# Race column(Race is the column with index 2) and save them in 
# 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively
# (Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

# Store the length of the above created arrays in 
# 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

# Find out which is the race with the minimum no. of citizens

# Store the number associated with the minority race in a variable 
# called 'minority_race'(For eg: if "len(race_5)" is the minimum, 
# store 5 in 'minority_race' because that is the index of the race 
# having the least no. of citizens )

In [ ]:
# QUESTION NUMBER 4

Race = dataAlt[:, [2]] # select column 2 from all the data(rows)
print(Race)

[[4]
 [4]
 [4]
 ...
 [4]
 [4]
 [4]]


In [ ]:
Race0 = np.where(Race == 0 )
print(Race0)

(array([ 15, 212, 226, 447, 516, 565, 596, 607, 903, 940]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))


In [ ]:
Race1 = np.where(Race == 1)
print(Race1)

(array([ 11,  14,  27,  93, 139, 152, 162, 163, 213, 255, 265, 297, 301,
       304, 311, 434, 455, 591, 652, 655, 668, 731, 873, 892, 916, 917,
       968]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0]))


In [ ]:
Race2 = np.where(Race == 2 )
print(Race2)

(array([  3,   4,   6,  10,  13,  21,  22,  31,  34,  45,  71,  92,  99,
       117, 122, 124, 134, 145, 157, 159, 176, 177, 180, 182, 185, 190,
       192, 206, 210, 215, 222, 223, 230, 231, 251, 252, 275, 282, 294,
       312, 313, 326, 330, 338, 339, 344, 373, 374, 410, 411, 418, 436,
       446, 450, 453, 457, 461, 484, 485, 505, 508, 511, 522, 532, 536,
       539, 553, 554, 563, 605, 608, 616, 621, 622, 625, 630, 631, 633,
       660, 667, 683, 691, 706, 707, 711, 715, 734, 736, 738, 747, 748,
       759, 785, 795, 797, 801, 811, 874, 876, 888, 890, 907, 914, 923,
       941, 945, 952, 978, 982, 986]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))


In [ ]:
Race3 = np.where(Race == 3 )
print(Race3)

(array([ 50, 233, 356, 404, 530, 784]), array([0, 0, 0, 0, 0, 0]))


In [ ]:
Race4 = np.where(Race == 4 )
print(Race4)

(array([   0,    1,    2,    5,    7,    8,    9,   12,   16,   17,   18,
         19,   20,   23,   24,   25,   26,   28,   29,   30,   32,   33,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   46,
         47,   48,   49,   51,   52,   53,   54,   55,   56,   57,   58,
         59,   60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
         70,   72,   73,   74,   75,   76,   77,   78,   79,   80,   81,
         82,   83,   84,   85,   86,   87,   88,   89,   90,   91,   94,
         95,   96,   97,   98,  100,  101,  102,  103,  104,  105,  106,
        107,  108,  109,  110,  111,  112,  113,  114,  115,  116,  118,
        119,  120,  121,  123,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  135,  136,  137,  138,  140,  141,  142,  143,  144,
        146,  147,  148,  149,  150,  151,  153,  154,  155,  156,  158,
        160,  161,  164,  165,  166,  167,  168,  169,  170,  171,  172,
        173,  174,  175,  178,  179,  181,  183,  

In [ ]:
Race00 = dataAlt[dataAlt[:,2] == 0 ]
print(Race00)
len_0 = len(Race00)
print(len_0)

len_0 = len(dataAlt[dataAlt[:,2] == 0 ])
print(len_0)
print("----------")



# test = dataAlt[dataAlt[:,2:5] == 0 ] # this gives you an error 
test = dataAlt[2] #prints all the elements in row 2
test = dataAlt[:,2] #prints all the rows and column 2
test = dataAlt[:,2] == 0  # it tells you wether 0 is found in column 2. thru all rows. true or false
test = dataAlt[dataAlt[:,2] == 0 ] # it outputs all the columns where 0 is found in column 2
# test = np.where(dataAlt[:,2] == 0 ) # this prints index of where 0 happens in column 2

print(test)

print("ttt")
print(dataAlt)

[[34  4  0  1  0  0 45  0]
 [35 10  0  0  0  0 40  0]
 [60  6  0  0  0  0 10  0]
 [51  9  0  1  0  0 40  0]
 [25 10  0  0  0  0 20  0]
 [20  9  0  1  0  0 48  0]
 [23 10  0  0  0  0 25  0]
 [29  9  0  1  0  0 40  0]
 [27 12  0  1  0  0 40  0]
 [31 12  0  0  0  0 40  0]]
10
10
----------
[[34  4  0  1  0  0 45  0]
 [35 10  0  0  0  0 40  0]
 [60  6  0  0  0  0 10  0]
 [51  9  0  1  0  0 40  0]
 [25 10  0  0  0  0 20  0]
 [20  9  0  1  0  0 48  0]
 [23 10  0  0  0  0 25  0]
 [29  9  0  1  0  0 40  0]
 [27 12  0  1  0  0 40  0]
 [31 12  0  0  0  0 40  0]]
ttt
[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]
 [50  9  4 ...  0 40  0]]


In [ ]:
Race11 = dataAlt[dataAlt[:,2] == 1 ]
print(Race11)
len_1 = len(Race11)
print(len_1)

len_1 = len(dataAlt[dataAlt[:,2] == 1 ])
print(len_1)

[[  30   13    1    1    0    0   40    1]
 [  40   11    1    1    0    0   40    1]
 [  54   10    1    1    0    0   60    1]
 [  30    9    1    0    0 1573   35    0]
 [  49   10    1    1    0    0   40    1]
 [  33   13    1    0    0    0   40    0]
 [  44   14    1    0    0    0   40    0]
 [  28    9    1    0    0    0   40    0]
 [  60    9    1    1    0    0   40    0]
 [  42    9    1    1    0    0   40    1]
 [  37   10    1    1    0    0   75    1]
 [  39   14    1    0 3464    0   40    0]
 [  21   10    1    0    0    0   25    0]
 [  24   10    1    0    0    0   40    0]
 [  34   14    1    1 7298    0   35    1]
 [  27   10    1    1    0 1980   40    0]
 [  40   11    1    1    0    0   40    1]
 [  55    9    1    0    0    0   40    0]
 [  35   16    1    1    0    0   40    1]
 [  29   10    1    0    0    0   40    0]
 [  20    7    1    0    0 1762   40    0]
 [  55   10    1    0    0    0   40    0]
 [  51   13    1    1    0 2415   40    1]
 [  28   11

In [ ]:
Race22 = dataAlt[dataAlt[:,2] == 2 ]
print(Race22)
len_2 = len(Race22)
print(len_2)

len_2 = len(dataAlt[dataAlt[:,2] == 2 ])
print(len_2)

[[  53    7    2    1    0    0   40    0]
 [  28   13    2    0    0    0   40    0]
 [  49    5    2    0    0    0   16    0]
 [  37   10    2    1    0    0   80    1]
 [  32   12    2    1    0    0   50    0]
 [  54    9    2    0    0    0   20    0]
 [  35    5    2    1    0    0   40    0]
 [  20   10    2    1    0    0   44    0]
 [  22   10    2    1    0    0   15    0]
 [  57   13    2    1    0    0   40    1]
 [  31   13    2    0    0    0   40    0]
 [  28   10    2    0    0    0   25    0]
 [  32    9    2    1    0    0   40    0]
 [  49   11    2    1    0    0   40    1]
 [  30   13    2    1    0    0   40    0]
 [  19   10    2    1    0    0   35    0]
 [  46   12    2    0    0    0   36    0]
 [  31    9    2    0    0    0   30    0]
 [  71   10    2    1    0 1816    2    0]
 [  42   13    2    1    0    0   50    0]
 [  21    9    2    1    0    0   40    0]
 [  34    9    2    1    0    0   40    0]
 [  44   10    2    1    0    0   38    1]
 [  30   10

In [ ]:
Race33 = dataAlt[dataAlt[:,2] == 3 ]
print(Race33)
len_3 = len(Race33)
print(len_3)

len_3 = len(dataAlt[dataAlt[:,2] == 3 ])
print(len_3)

[[  25   10    3    0    0    0   40    0]
 [  33   10    3    0    0    0   40    0]
 [  65    7    3    1    0    0   40    0]
 [  28    4    3    1    0 2179   40    0]
 [  44    7    3    0    0    0   46    0]
 [  40   13    3    0    0    0   55    1]]
6
6


In [ ]:
Race44 = dataAlt[dataAlt[:,2] == 4 ]
print(Race44)
len_4 = len(Race44)
print(len_4)

len_4 = len(dataAlt[dataAlt[:,2] == 4 ])
print(len_4)

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]
 [50  9  4 ...  0 40  0]]
848
848


In [ ]:
Race55 = dataAlt[dataAlt[:,2] == 5 ]
print(Race55)
len_5 = len(Race55)
print(len_5)

len_5 = len(dataAlt[dataAlt[:,2] == 5 ])
print(len_5)

[]
0
0


In [ ]:
# Step 5: As per govt. records citizens above 60 should not work more than 25 
# hours a week. Let us check if the policy is in place

# Create a new subset array called 'senior_citizens' by filtering 
# 'census' according to age>60 (age is the column with index 0)

# Add all the working hours(working hours is the column with index 6) 
# of 'senior_citizens' and store it in a variable called 'working_hours_sum'

# Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

# Finally find the average working hours of the senior citizens 
# by dividing 'working_hours_sum' by 'senior_citizens_len' and store 
# it in a variable called 'avg_working hours'.

# Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
seniorCitizens = dataAlt[dataAlt[:,0] > 60 ]
print(seniorCitizens)
print("yyyy")
# test = dataAlt[2] #prints all the elements in row 2
# test = dataAlt[:,2] #prints all the rows and column 2
# test = dataAlt[:,2] == 0  # it tells you wether 0 is found in column 2. thru all rows. true or false
test = dataAlt[dataAlt[:,2] == 0 ] # it outputs all the rows where 0 is found in column 2
# test = np.where(dataAlt[:,2] == 0 ) # this prints index of where 0 happens in column 2
print(test)

[[   79    10     4     1     0     0    20     0]
 [   67     6     4     1     0     0     2     0]
 [   76    14     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     0]
 [   70    10     4     1     0     0    40     0]
 [   64     7     4     1     0  2179    40     0]
 [   71    10     2     1     0  1816     2     0]
 [   68     2     4     0     0     0    20     0]
 [   66    11     4     0     0     0    20     0]
 [   64     2     4     1     0     0    40     0]
 [   90     9     2     1     0  2206    40     0]
 [   66     9     4     1  1409     0    50     0]
 [   75    11     4     0     0     0    20     0]
 [   65     9     4     0     0     0    40     0]
 [   64     9     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     1]
 [   65     9     4     1     0     0    16     0]
 [   77    10     4     1     0     0    40     0]
 [   62     9     4     0     0     0    24     0]
 [   76    14     4     1     0

In [ ]:
working_hours_sum = sum(seniorCitizens)
print(working_hours_sum)
print("yes")
print(working_hours_sum[6])

[ 4129   549   232    44 47576 10945  1917    13]
yes
1917


In [ ]:
working_hours_sum[6]

1917

In [ ]:
seniorCitizensLength = len(seniorCitizens)
print(seniorCitizensLength)

61


In [ ]:
avg_working_hours = (working_hours_sum[6]/seniorCitizensLength)
print(avg_working_hours)

31.42622950819672


In [ ]:
# Step 6: Let's check that higher educated people have better pay in general.

# Create two new subset arrays called 'high' and 'low' by filtering 'census' 
# according to education-num>10 and education-num<=10 (education-num is the 
# column with index 1) respectively.

# Find the mean of income column(income is the column with index 7) 
# of 'high' array and store it in 'avg_pay_high'. Do the same 
# for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
high = dataAlt[dataAlt[:,1] >= 10 ]
print(high)

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [28 13  2 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]


In [ ]:
AgeMean = np.average(dataAlt)
# print(round(AgeMean, 2))  # decimal trick

In [ ]:
av=sum(high[:,7])/len(high[:,7])*100
print(av)
print(len(high[:,7]))

31.70289855072464
552


In [ ]:
# seniorCitizens = dataAlt[dataAlt[:,0] > 60 ]
# print(seniorCitizens)
# print("yyyy")
# # test = dataAlt[2] #prints all the elements in row 2
# # test = dataAlt[:,2] #prints all the rows and column 2
# # test = dataAlt[:,2] == 0  # it tells you wether 0 is found in column 2. thru all rows. true or false
# test = dataAlt[dataAlt[:,2] == 0 ] # it outputs all the rows where 0 is found in column 2
# # test = np.where(dataAlt[:,2] == 0 ) # this prints index of where 0 happens in column 2
# print(test)

In [ ]:
np.mean(dataAlt[:7])

49.94642857142857

In [ ]:
a = sum(dataAlt)
print("hola")
len(dataAlt)
print(a)

hola
[ 38101  10093   3657    672 588526  92960  39916    232]


In [ ]:
promedio = np.mean(dataAlt[:7])
print(promedio)

49.94642857142857


In [ ]:
col7 = sum(dataAlt)
print(col7)
print("yes")
print(col7[6])
col7[6]
lencol7 = len(col7)
print(lencol7)
avg_Money = (col7/lencol7)
print(avg_Money)

[ 38101  10093   3657    672 588526  92960  39916    232]
yes
39916
8
[4.762625e+03 1.261625e+03 4.571250e+02 8.400000e+01 7.356575e+04
 1.162000e+04 4.989500e+03 2.900000e+01]


In [ ]:
sumaIngreso= sum(dataAlt)
cuantosIndexHay = len(dataAlt[:,7] == 1)
print(cuantosIndexHay)
print(sumaIngreso[7])

1001
232


In [ ]:
sumatoriaAt1 = sum(dataAlt[dataAlt[:,7] == 1])

In [ ]:
print(sumatoriaAt1)

[ 10113   2705    867    191 455716  42338  10532    232]


In [ ]:
sumatoriaBelow1 = sum(dataAlt[dataAlt[:,7] == 0])

In [ ]:
len(dataAlt)  - (sumatoriaAt1)

array([  -9112,   -1704,     134,     810, -454715,  -41337,   -9531,
           769])

In [ ]:
suma = sum(dataAlt)

In [ ]:
print(suma)

[ 38101  10093   3657    672 588526  92960  39916    232]


In [ ]:
high = suma[7]
print(high)

232


In [ ]:
largo = len(dataAlt)
print(largo)

1001


In [ ]:
low = largo - suma[7]
print(low)

769


In [ ]:
# how many ppl are above 10 years of 
# education and out of those how many are with a 1 or a zero

In [ ]:
#how many people above 10 years and income of 1


# ppl above and = 10
Above10 = dataAlt[dataAlt[:,1]>=10]
# print(Above10)

# incomeOf1 = sum(dataAlt[7]) # this is a horrible!!!

finalIntersection = Above10[Above10[:,7]==1]
print(finalIntersection)
totalEq1 = len(finalIntersection)
print(totalEq1)
len(Above10)
perctOfAbove10ANDeaqual1 = totalEq1/len(Above10) 
print(round(perctOfAbove10ANDeaqual1*100, 3), "%")
# print(len(Above10))

[[31 14  4 ...  0 50  1]
 [42 13  4 ...  0 40  1]
 [37 10  2 ...  0 80  1]
 ...
 [40 14  4 ...  0 35  1]
 [48 13  4 ...  0 58  1]
 [39 13  4 ...  0 50  1]]
175
31.703 %


In [ ]:
aboveD = dataAlt[dataAlt[:,1]>=10]
print(aboveD)
print("kkk")
high= aboveD[aboveD[:,7]==1]
print(len(high))
low = 1- (len(high)/len(aboveD))
print(low)

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [28 13  2 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]
kkk
175
0.6829710144927537
